baseurl = "https://example.com"
languageCode = "en"
title = "Hemingway wrote"
theme = "hemingway3"
copyright = "&copy; <a href=\"https://github.com/tanksuzuki\">Asuka Suzuki</a> 2017"
disqusShortname = "shortname"
googleAnalytics = ""

[taxonomies]
tag = "tags"
category = "categories"

[params.meta]
description = "Your personal description"
keywords = ["keyword1", "keyword2"]
name = "Asuka Suzuki"

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/tanksuzuki"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/beli3ver"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/tanksuzuki"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://telegram.me/beli3ver"
fa_icon = "fa-telegram"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
